### ISSUE TITLE
How to run precompiled release binaries?

### ISSUE THREAD

**Issue by jbabyhacker** [est31/cargo-udeps#104]
On the releases page, I see you have precompiled binaries. However, I am running into some difficulty running it. Basically it requires the nightly compiler to run. Compiling it with nightly still doesn't allow it to run.

> error: the option `Z` is only accepted on the nightly compiler

I am using this in a docker image, and would like to add the binary without having to compile it.

**Comment by est31** [comment]
As the error message, as well as the README of cargo-udeps says, you need the nightly compiler available. Do `rustup install nightly` then `cargo +nightly udeps` (if you have rustup, other ways of obtaining rustc differ).
