### ISSUE TITLE
using the `DepInfo` backend still uses `-Z save-analysis`

### ISSUE THREAD

**Issue by pvdrz** [est31/cargo-udeps#106]
Hi, I'm not sure if this is intended or not but I found an upstream bug (binary-dep-depinfo) that causes an ICE on rustc with the `-Z save-analysis` flag on and by extension while calling `cargo +nightly udeps`: https://github.com/rust-lang/rust/issues/88536. 

I know that there is the `--backend depinfo` flag but it seems that the command executed by the compiler still includes the `save-anaysis` flag. Is this the intended behavior?

**Comment by est31** [comment]
I'm not entirely sure if this flag should stay. There might be some caching implications. That is, if you don't pass the flag, run `cargo udeps`, and then pass it, cargo might think it already ran that command and thus not execute it. But I'm not entirely sure. It can be figured out experimentally, and I can't think of any other issue than that one.

**Comment by pvdrz** [comment]
I have a local copy of the repo removing the flag when the `depinfo` backend is being used. I'll test if your caching issues happen or not.

**Comment by pvdrz** [comment]
I did this experiment: 
- Run `cargo +nightly udeps --backend=depinfo` in a crate without dependencies.
- Add a dependency to the manifest and don't use it.
- Run `cargo +nightly udeps --backend=depinfo` again.
The unused dependecy is detected in the second run. Is that OK or do you think I should try something more extensive?

**Comment by est31** [comment]
> Is that OK or do you think I should try something more extensive?

My concern was more what if you did, after removing the target dir, run `cargo +nightly udeps --backend=depinfo` first and then ran `cargo +nightly udeps`. Does it then still warn about an unused dependency that you added before removing the target dir?

**Comment by pvdrz** [comment]
it still warns me in both runs but the first run does the checks from scratch ( as expected ) and then the second run reuses the `json`.
