### ISSUE TITLE
cargo-udeps gives false negative

### ISSUE THREAD

**Issue by tisonkun** [est31/cargo-udeps#108]
From https://github.com/engula/engula main nightly (965d3d9c5c00941fc91b386d7e82d76d214ec64d), [this dep](https://github.com/engula/engula/blob/965d3d9c5c00941fc91b386d7e82d76d214ec64d/src/microunit/Cargo.toml#L10) is redundant. But cargo-udeps cannot spot it.

**Comment by est31** [comment]
Yeah this is because hyper is a dependency of reqwest and cargo-udeps can't recognize unused dependencies if they are used by some other dependency. This is one of the known limitations, see #84.

**Comment by tisonkun** [comment]
OK. Thanks for your explanation.
