### ISSUE TITLE
Nightly requirement

### ISSUE THREAD

**Issue by andrewbanchich** [est31/cargo-udeps#113]
I see the README says udeps requires nightly to run, but doesn't say why.

Is there a tracking issue for when it will be able to run on stable? We currently use it in our CI pipelines but would prefer to use it on stable to avoid nightly breaking changes.

**Comment by est31** [comment]
cargo-udeps has two backends, one based on depinfo, the other on save-analysis. Save-analysis is permanently unstable: https://github.com/rust-lang/rust/issues/43606 , but the depinfo backend has a chance of being stabilized: https://github.com/rust-lang/rust/issues/63012
