### ISSUE TITLE
nushell

### ISSUE THREAD

**Issue by fdncred** [est31/cargo-udeps#130]
sorry to post this here, not sure how else to contact you @est31. we recently reached 20k stars on nushell and invited everyone with more than 20 PRs to a discord club https://discord.gg/NtAbbGn. you met that criteria easily and I wanted to invite you and say we miss you contributing to nushell. we wish you much success and thanks for all your contributions.

**Comment by est31** [comment]
Thanks! Yes, I've been involved in the project shortly after publication and have contributed for a while in a project to move it to stable Rust.
