### ISSUE TITLE
Minor (cosmetic) - could `Loading save analysis` messages be suppressed?

### ISSUE THREAD

**Issue by aldanor** [est31/cargo-udeps#138]
Those are definitely useful as verbose/debug info but most of the time, why would the user care? Could they be hidden behind a verbose flag or even easier, and env var? (e.g. `CARGO_UDEPS_VERBOSE`)

Asking because the typical use case is...

```
$ cargo +nightly udeps

<2 pages of 'info: Loading save analysis from ...'>
All deps seem to have been used.
```

(apologies in advance if I'm missing something obvious here)

**Comment by est31** [comment]
Hmm yeah I'm open to adding an option for it, opt-in even. Maybe we should control this via rust logging levels?

**Comment by aldanor** [comment]
> Hmm yeah I'm open to adding an option for it, opt-in even. Maybe we should control this via rust logging levels?

Opt-in with rust log levels sounds great. (Because that's what it looks like anyway - a debug/trace-level internal log).
