### ISSUE TITLE
confusing error message about nightly compiler

### ISSUE THREAD

**Issue by rizsotto** [est31/cargo-udeps#14]
Hi,

I've read about your tool and wanted to see what it can do on my project. (It's this [repo](https://github.com/rizsotto/Bear/tree/3.x), the branch name is `3.x`) Got this error message:

`error: the option 'Z' is only accepted on the nightly compiler`

The project is using stable (and not the nightly) compiler. Could not find how to run more verbose this tool. Any hint what could be the problem?

**Comment by est31** [comment]
Right now, cargo-udeps needs Rust nightly to run, as it relies on unstable features. Once #4 is implemented, this will be different but for now, Nightly is needed. You can run cargo udeps doing: `cargo +nightly udeps`.
