### ISSUE TITLE
Is there a --check flag or something similar?

### ISSUE THREAD

**Issue by Jasperav** [est31/cargo-udeps#144]
I want to integrate this library into my CI. I was wondering if there was a --check flag or anything related so the CI will fail when an unused dependency is has been found.

**Comment by est31** [comment]
`cargo-udeps` already returns a non 0 exit code if it finds unused dependencies. So I don't think such a flag would be neccessary?

**Comment by est31** [comment]
I hope this answered the question. Otherwise, speak!
