### ISSUE TITLE
possibly surprising behavior for `--expect`?

### ISSUE THREAD

**Issue by danhhz** [est31/cargo-udeps#146]
Howdy!

Materialize (https://github.com/MaterializeInc/materialize) recently introduced the usage of https://crates.io/crates/cargo-hakari to generate a "workspace-hack" crate containing all of our third party deps and the union of the features we use on those deps. We've been using cargo-udeps and would like to continue to use it for detecting unused deps between the materialize crates, but to do that we'd need to opt out the workspace-hack crate. I feel good about using `package.metadata.cargo-udeps.ignore` to handle the individual crates's dependencies on workspace-hack, but workspace-hack itself has a bunch of unused deps.

The `--exclude` flag sounds like exactly what I'd want for this, but I couldn't quite figure out what it's actually affecting: I.e. `RUSTUP_TOOLCHAIN=nightly cargo udeps --workspace --all-targets --exclude workspace-hack` seems to do the same thing as if I don't specify --exclude.

Is there something I'm missing?

Fwiw, this patch gets the behavior I'd expect. It doesn't seem like the best way to effect the change, so I'm not bothering to open it as a pull request, but happy to do that with direction on the design (assuming this is indeed a bug and not a mis-usage).

Thanks!

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 8185c3d..d60a63f 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -477,12 +477,20 @@ impl OptUdeps {
 
 		let mut outcome = Outcome::default();
 
+		let package_id_specs = compile_opts.spec.to_package_id_specs(&ws)?;
 		for (dependencies, used_dependencies, kind) in &[
 			(&normal_dependencies, &used_normal_dev_dependencies, dependency::DepKind::Normal),
 			(&dev_dependencies, &used_normal_dev_dependencies, dependency::DepKind::Development),
 			(&build_dependencies, &used_build_dependencies, dependency::DepKind::Build),
 		] {
 			for &(id, dependency) in *dependencies {
+				// WIP seems like there should be a better way than iterating
+				// package_id_specs each time
+				let interesting_package = package_id_specs.iter().any(|x| x.matches(id));
+				if !interesting_package {
+					continue;
+				}
+
 				use anyhow::Context;
 				let ignore = ws_resolve
 					.pkg_set
```

**Comment by est31** [comment]
Hi and thanks for using cargo-udeps! Regarding `--exclude` not working, that flag is not used by cargo-udeps itself but by the `cargo check` call it is invoking. It would make sense to support it for cargo-udeps as well, probably under that same name.

Regarding your patch, it looks pretty good already. I guess you could turn `package_id_specs` into a hashset or something to make it faster?

**Comment by danhhz** [comment]
Thanks for the reply! I figured out how to make that into a `HashSet<PackageId>` so went ahead and opened a PR https://github.com/est31/cargo-udeps/pull/147
