### ISSUE TITLE
v0.1.36 release does not contain pre-built binaries in the assets section

### ISSUE THREAD

**Issue by reubenmiller** [est31/cargo-udeps#157]
The latest release [v0.1.36](https://github.com/est31/cargo-udeps/releases/tag/v0.1.36) does not contain the pre-built binaries.

This means that other tooling such as [aig787/cargo-udeps-action](https://github.com/aig787/cargo-udeps-action) fails when using the `latest` tag (as it only tries to install pre-built binaries, and does not build from the source code (though this is also a feature gap from that project imho)).

Though all previous releases seem to include the pre-built assets, so I'm assuming that they were just accidentally left out from the release.

Below shows a screenshot of the current assets from [v0.1.36](https://github.com/est31/cargo-udeps/releases/tag/v0.1.36)

![image](https://user-images.githubusercontent.com/3029781/235604403-e011a58b-d2b8-47a5-84a2-6a3c198595a9.png)

**Expected behaviour**

* Add pre-built binaries for the following targets:
  * cargo-udeps-v0.1.36-x86_64-apple-darwin.tar.gz
  * cargo-udeps-v0.1.36-x86_64-pc-windows-msvc.zip
  * cargo-udeps-v0.1.36-x86_64-unknown-linux-gnu.tar.gz

**Comment by reubenmiller** [comment]
I was probably too quick in creating the issue, I see there is already some [actions underway](https://github.com/est31/cargo-udeps/actions/runs/4857977885) to fix the problem 🥇

**Comment by est31** [comment]
Closing this as [0.1.38 has artifacts](https://github.com/est31/cargo-udeps/releases/tag/v0.1.38).
