### ISSUE TITLE
error message accidentally debug printed?

### ISSUE THREAD

**Issue by matthiaskrgr** [est31/cargo-udeps#19]
When checking clippy:
````
Error: StrErr("current implementation cannot handle multiple crates with the same `lib` name:\n`clippy v0.0.212 (/home/matthias/vcs/github/rust-clippy)`\n├── \"rustc_tools_util\" → \"rustc_tools_util\"\n├── \"rustc_tools_util\" → \"rustc_tools_util\"\n└── ..")
````

Is this some accidental debug print which should be a normal print?

**Comment by est31** [comment]
In theory this should terminate the program. It's not a debug print but points to a current limitation in the cargo-udeps implementation.

**Comment by matthiaskrgr** [comment]
I was wondering because of all the literal `\n`s in the `StrErr()`.

**Comment by est31** [comment]
Oh, right. Yeah it is being debug printed due to the Termination trait: https://doc.rust-lang.org/stable/std/process/trait.Termination.html

In this case this seems like subpar UX. I guess we'll have to implement Debug for StrErr manually.
