### ISSUE TITLE
unknown unstable option: `save-analysis`

### ISSUE THREAD

**Issue by xerenahmed** [est31/cargo-udeps#193]
Run: `cargo +nightly udeps`
```
error: unknown unstable option: `save-analysis`

error: could not compile `app_macros`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Project has workspace and a macro lib named `app_macros` as seen in the error message

**Comment by est31** [comment]
You seem to be running an old version of cargo-udeps that still wants to use the save-analysis backend. The default was changed [about a year ago](https://github.com/est31/cargo-udeps/blob/master/CHANGELOG.md#release-0133---september-15-2022). I think an update of cargo-udeps will resolve your problems.
