### ISSUE TITLE
Current implementation cannot handle multiple crates with the same `lib` name

### ISSUE THREAD

**Issue by baumanj** [est31/cargo-udeps#22]
When running `cargo +nightly udeps` against https://github.com/habitat-sh/habitat:
```
➤ cargo +nightly udeps
  Downloaded arc-swap v0.4.2
  Downloaded chrono v0.4.9
…
  Downloaded 34 crates (4.0 MB) in 8.13s (largest was `encoding_rs` at 1.4 MB)
Error: StrErr("current implementation cannot handle multiple crates with the same `lib` name:
`habitat_core v0.0.0 (/home/jbauman/habitat/components/core)`
├── "base64" → "base64"
├── "base64" → "base64"
└── ..")
```

I know
> Crates are currently only handled on a per name basis. Two crates with the same name but different versions would be a problem.

is listed as a known bug in https://github.com/est31/cargo-udeps/blob/master/README.md#known-bugs, but I couldn't find an issue that's tracking it. Since the project I work on won't be able to make use of `udeps` until this is resolved, having an issue I can subscribe to will help ensure that I can use it when that bug is fixed.

**Comment by est31** [comment]
Yes, in this instance the crate is used both as build dependency and normal dependency. I've ran into this multiple times myself. Thanks for filing the bug.

**Comment by baumanj** [comment]
Thanks for the tool! It promises to be really helpful

**Comment by est31** [comment]
PRs to fix it are welcome!

**Comment by qryxip** [comment]
@metajack The problem can be fixed by this. (I don't know why)

```diff
   for (to_pkg, deps) in resolve.deps(from) {
+     // `Resolve::deps` rarely returns multiple same `Dependenc`ies.
+     let deps = deps.iter().collect::<BTreeSet<_>>();
```

But unfortunately `cargo-udeps` still does not work for `libra` because `admission_control_service` depends on both `futures` v0.1 and `futures` v0.3.

```
Error: StrErr("current implementation cannot handle multiple crates with the same `lib` name:
`admission_control_service v0.1.0 (/home/ryo/src/libra/admission_control/admission_control_service)`
└── (dev-)dependencies
    ├── "futures03" → "futures"
    ├── "futures" → "futures"
    └── ..")
```

```toml
[dependencies]
futures = "0.1.28"
futures03 = { version = "=0.3.0-alpha.17", package = "futures-preview" }
```

**Comment by qryxip** [comment]
Still not working even thought replacing `futures` v0.1 with [`futures01`](https://crates.io/crates/futures01).
Thought I wrote the error, The error should be probably a warning.
```
Error: StrErr("current implementation cannot handle multiple crates with the same `lib` name:
`libra_wallet v0.1.0 (/home/ryo/src/libra/client/libra_wallet)`
└── (dev-)dependencies
    ├── "rust-crypto" → "crypto"
    ├── "libra_crypto" → "crypto"
    └── ..")
```
