### ISSUE TITLE
Support `workspace.metadata.cargo-udeps.ignore` to ignore dependencies in whole workspace

### ISSUE THREAD

**Issue by cmtm** [est31/cargo-udeps#231]
I'd like to add support for ignoring packages in a workspace `Cargo.toml`. As of now, the ignored dependencies can only be specified in a package's `Cargo.toml`. The main use-case for this would be to support using something like [cargo hakari](https://crates.io/crates/cargo-hakari) alongside udeps. I can come up with PR if you're open to this funtionality.

**Comment by cmtm** [comment]
PR with feature: https://github.com/est31/cargo-udeps/pull/232

**Comment by est31** [comment]
The PR is merged now, thanks!

**Comment by cmtm** [comment]
@est31 , any idea when we'll get a release? I'd like to use the released udeps in our workflow, but we can't until the commit in #232 gets released.

**Comment by est31** [comment]
@cmtm 0.1.45 is released now, including your PR.
