### ISSUE TITLE
0.1.46 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [est31/cargo-udeps#256]
👋 it looks like [0.1.46 release build](https://github.com/est31/cargo-udeps/actions/runs/7855155284/job/21436588082) did not pass thru, raise this issue for some awareness. Thanks!

cc @est31 

relates to https://github.com/Homebrew/homebrew-core/pull/162283

**Comment by est31** [comment]
Would it be possible to point to a git hash for the current 0.1.46 release? If not, I'm also ready to make a new one, I just prefer former approach as it's more simple.

**Comment by chenrui333** [comment]
@est31 I think it would be better to just make a new release and roll forward.

**Comment by chenrui333** [comment]
any luck of creating a new release? Thanks!

**Comment by est31** [comment]
Ok I have release 0.1.47 now with an updated lockfile. Sorry for the delay.

**Comment by chenrui333** [comment]
np, thanks @est31!
