### ISSUE TITLE
False positive error

### ISSUE THREAD

**Issue by u2** [est31/cargo-udeps#28]
https://github.com/nervosnetwork/ckb/blob/develop/util/instrument/Cargo.toml#L10

It should be a used dependency, but cargo-udeps tells me it's unused.

**Comment by est31** [comment]
Can you paste the exact command you used? Specifically, have you enabled any features when you ran cargo-udeps?

**Comment by qryxip** [comment]
Or rather, aren't you using v0.1.4 on crates.io? The `master` `cargo-udeps` [distinguishes `build-dependencies` from `(dev-)dependencies`](https://github.com/est31/cargo-udeps/pull/24).
 
![screenshot](https://user-images.githubusercontent.com/14125495/65711056-16fc5b00-e0cf-11e9-92ee-d13a2e818892.png)

**Comment by est31** [comment]
That's a good point! Before we make a new cargo release I originally wanted to build a small test suite first, see #3. I think I'll get right to it in the evening.

**Comment by est31** [comment]
0.1.5 has been released. Please write if you are still getting the bug.
