### ISSUE TITLE
Run against OpenSSL 3.x

### ISSUE THREAD

**Issue by MLNW** [est31/cargo-udeps#282]
I wanted to test use this package on a newer Ubuntu instance. It comes with OpenSSL 3.x installed. When I run `cargo +nightly udeps` I get this error:

```
/home/dev/.cargo/bin/cargo-udeps: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Looking through the web Ubuntu seems to have upgraded to OpenSSL 3.x for a while now. Is there a way to get it running with it?

I already tried building OpenSSL 1.1 from source but that didn't get me any further and it feels quite bad trying to downgrade this. I took instructions from here: https://askubuntu.com/a/1458747

**Comment by est31** [comment]
@MLNW I think you'll need to rebuild cargo-udeps. What does `stat /home/dev/.cargo/bin/cargo-udeps` say? Probably some earlier date.

`cargo install cargo-udeps --reinstall` should fix it.

**Comment by MLNW** [comment]
I ran `cargo install cargo-udeps --force` since there is no `--reinstall` flag. That seems to have worked. Though I'm surprised. This is a completely fresh setup. Oh well. Thanks for the hint. For some reason it worked ...
