### ISSUE TITLE
Lockfile v2

### ISSUE THREAD

**Issue by MikailBag** [est31/cargo-udeps#41]
When I tried switch my project to [Cargo.lock v2](https://github.com/rust-lang/cargo/pull/7579), I got error: 
`
Error: StrErr("failed to parse lock file at: /home/runner/work/jjs/jjs/Cargo.lock")
`

**Comment by est31** [comment]
@MikailBag StrErr should be gone actually. Do you have the latest version of cargo-udeps?

**Comment by est31** [comment]
Hmmm maybe I should do a new crates.io release...

**Comment by est31** [comment]
New crates.io release is out. I hope this resolves this issue, if not please say so
