### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by thomaseizinger** [est31/cargo-udeps#42]
I am thinking of writing a GitHub action that runs `cargo-udeps` against a repository and opens a PR that removes the unused dependencies.

To achieve this, it would be nice if the command would have a flag to produce machine-readable output (JSON?).

**Comment by qryxip** [comment]
That sounds good. What kind of information is necessary for the Action? How about this?

```
unused dependencies:
`foo v0.0.0 (/home/me/src/foo)`
└─── (dev-)dependencies
     ├─── "counter"
     ├─── "indexmap"
     └─── "url1"
```

↓

```json
{
  "cli_options": {
    "all_targets": true,
    "..": ".."
  },
  "success": false,
  "workspace": {
    "foo 0.0.0 (path+file:///home/me/src/foo)": {
      "manifest_path": "/home/me/src/foo/Cargo.toml",
      "unused_dependencies": {
        "normal": {
          "counter": {
            "package_name": "counter",
            "version_req": "^0.4.3",
            "resolve": "counter 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)"
          },
          "indexmap": {
            "package_name": "indexmap",
            "version_req": "^1.3.0",
            "resolve": "indexmap 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
          },
          "url1": {
            "package_name": "url",
            "version_req": "^1.7.2",
            "resolve": "url 1.7.2 (registry+https://github.com/rust-lang/crates.io-index)"
          }
        },
        "dev": {},
        "build": {}
      }
    }
  }
}
```

**Comment by thomaseizinger** [comment]
> What kind of information is necessary for the Action?

1. Path to the Cargo.toml that is being inspected (needs to handle workspaces correctly)
2. A list of the dependencies that are outdated (I am planning to pass the result to `cargo rm` from the `cargo-edit` subcommand)

What are you proposing seems to contain all this information, and much more :)

Up to you to decide how much you actually want to expose / commit to.

How does `cargo-udeps` actually figure out, which dependencies are unused? Would it be somehow possible to have `cargo-udeps` already emit a `Cargo.toml` that has the dependencies removed?

That would save us some round-tripping of parsing output and editing the `Cargo.toml` file again :D
