### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by frol** [est31/cargo-udeps#69]
I created AUR package for Arch Linux: https://aur.archlinux.org/packages/cargo-udeps/

The installation instructions for Arch Linux users:

```
yay -S cargo-udeps
```

**Describe the solution you'd like**

I suggest adding this (as installation instructions or just a mention of the link) to the README

**Comment by est31** [comment]
Thanks! There is also a nixos package. I think mentions of both can be added to the README.
