### ISSUE TITLE
Canno open shared object file: libgit2.so.1.0 

### ISSUE THREAD

**Issue by dessalines** [est31/cargo-udeps#83]
I fixed the below error by doing `sudo ln -s /usr/lib/libgit2.so.1.1 /usr/lib/libgit2.so.1.0`

```
❯ cargo +nightly udeps
/home/xxx/.cargo/bin/cargo-udeps: error while loading shared libraries: libgit2.so.1.0: cannot open shared object file: N
o such file or directory
```

**Comment by est31** [comment]
@dessalines have you updated your system? Maybe you only have to reinstall cargo-udeps?

**Comment by dessalines** [comment]
I did update my system, and then tried updating cargo-udeps, and for some reason it still had the issue. I wonder what dependency relies on libgit2.so

**Comment by est31** [comment]
@dessalines cargo-udeps uses cargo internally as a library. cargo in turn needs it in order to work with git dependencies.

**Comment by dessalines** [comment]
Ah, its a cargo issue then, nothing to do with cargo-udeps.
