### ISSUE TITLE
Show unused dependencies that gets used transitively by other dependecies

### ISSUE THREAD

**Issue by WiSaGaN** [est31/cargo-udeps#84]
Currently, `cargo +nightly udeps` shows `All deps seem to have been used.` for below:
```Cargo.toml
[dependencies]
chrono = "0.4"
time = "0.1"
```
```rust
fn main() {
    println!("{:?}", chrono::Local::now());
}
```

I expect it to show `time` dependency as unused since we can remove it from `Cargo.toml`. I am not sure whether this should be a bug issue or a feature request though.

Very useful tool by the way!

**Comment by dodomorandi** [comment]
Same thing here: [in this repo](https://github.com/dodomorandi/josekit-rs/tree/remove-unsafe) (already merged) the `foreign-types` crate is *directly unused*, but `openssl` depends on that and the tool does not show that the dependency could be removed from `Cargo.toml`.

**Comment by light4** [comment]
I write a small tool for this.
https://github.com/light4/cargo-inner
