### ISSUE TITLE
feature `resolver` is required

### ISSUE THREAD

**Issue by SOF3** [est31/cargo-udeps#98]
When I run `cargo udeps` on a project with the dependency `nalgebra = "0.27.0"`, I fail with this error:

```
error: failed to download `nalgebra v0.27.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/sofe/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.27.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

Probably relevant:

https://github.com/dimforge/nalgebra/blob/dfc8ad3d6ac7af455ef59a69eb5baa9a8e15f2a6/Cargo.toml#L105

**Comment by est31** [comment]
@SOF3 what is your cargo udeps version? Do you use the latest release?

**Comment by SOF3** [comment]
Sorry, it's fixed after I run `rustup update`.
