### ISSUE TITLE
error[E0658]: use of unstable library feature 'bool_to_option'

### ISSUE THREAD

**Issue by twhiteheadzm** [est31/cargo-udeps#99]
When attempting to install as per instructions on crates.io I get error:

`error[E0658]: use of unstable library feature 'bool_to_option'`

Ubuntu 18.04 running inside WSL.
I have a specific nightly as default:
`nightly-2020-10-01-x86_64-unknown-linux-gnu (default)`

So I tried the install with +stable and also with +nightly but see the same above error.

**Comment by qryxip** [comment]
I think the `stable` channel and the `nightly` channel are also old.

[`bool::then`](https://doc.rust-lang.org/stable/std/primitive.bool.html#method.then) is no longer featere-gated since Rust 1.50.

**Comment by twhiteheadzm** [comment]
Thanks. I updated rust and that fixed the install. Now experiencing an issue when running it with a particular crate not compiling which seems to cause the whole process to fail. But that is a separate issue.
